name: 🐛 Bug Report
description: Report a bug or issue with react-cache-refresh
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version of react-cache-refresh
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install react-cache-refresh
        2. Use the hook/component like...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g. macOS, Windows, Linux]
        - Browser: [e.g. Chrome, Firefox, Safari]
        - Node.js version: [e.g. 18.17.0]
        - React version: [e.g. 18.2.0]
        - react-cache-refresh version: [e.g. 1.0.1]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable
      placeholder: Any additional information that might help...

  - type: textarea
    id: logs
    attributes:
      label: Error logs/Console output
      description: If applicable, add any error messages or console output
      render: shell
